version: 2.1
orbs:
  aws-cli: circleci/aws-cli@5.1
jobs:
  build:
    docker:
      - image: cimg/node:20.11.1
    working_directory: ~/organic-code
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
      - run: npm run build
  deploy:
    docker:
      - image: cimg/node:20.11.1
    working_directory: ~/organic-code
    environment:
      - NODE_ENV: production
    steps:
      - checkout
      - restore_cache:  # Restore the saved cache
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-
      - run: npm install
      - save_cache:
          key: v2-dependencies-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: create a production react build
          command: npm run build
      - aws-cli/install
      - run:
          name: Deploy to S3
          command: |
            [ -f ~/organic-code/build/index.html ] || exit 1
            aws s3 sync ~/organic-code/build $S3_BUCKET --delete
      - run:
          command: |
            aws cloudfront create-invalidation \
            --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths /index.html

workflows:
  build-deploy:
    jobs:
      - build
      # - test:
      #     requires:
      #       - build
      # - lint:
      #     requires:
      #       - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
