# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11.0
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
    working_directory: $CIRCLE_WORKING_DIRECTORY
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: apk update && apk add git
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      - run: yarn test
  deploy:
    working_directory: $CIRCLE_WORKING_DIRECTORY
    steps:
      -run:
          name: create a production react build
          command: yarn build
      -run:
          name: install AWS CLI (first install pip, the Python package manager)
          command: |
            apk add --update python python-dev py-pip build-base
            pip install awscli
      -run:
          command: |
            aws s3 sync ~/build $S3_BUCKET --delete --recursive
      -run:
          command: |
            aws cloudfront create-invalidation
            --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths /*

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
      # - test:
      #     requires:
      #       - build
      # - lint:
      #     requires:
      #       - build
      - deploy:
          # requires:
          #   - lint
          #   - test
          filters:
            branches:
              only:
                - deploy_with_circle
